export const githubTypes = {
  FETCH_ADD_GITHUB_LIST_START: "FETCH_ADD_GITHUB_LIST_START",
  FETCH_ADD_GITHUB_LIST_SUCCESS: "FETCH_ADD_GITHUB_LIST_SUCCESS",
  FETCH_ADD_GITHUB_LIST_FAILURE: "FETCH_ADD_GITHUB_LIST_FAILURE",
};
